# Modifed originally from LGUG2Z's `Vim-like` configurations located here: https://github.com/LGUG2Z/helix-vim 
# 
# Would recommend starting from there for a base configuration. 

theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
auto-format = false 
cursorline = true

[editor.gutters.line-numbers]
min-width = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal."space"]
"minus" = "jump_backward"
"space" = ":write"
p = "paste_clipboard_after"
q = ":bc"
y = "yank_main_selection_to_clipboard"

[keys.normal]
# Quick iteration on config changes
"minus" = "goto_definition"
v = ["select_mode", "search_selection"]

# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

# Muscle memory
"$" = "goto_line_end"
"%" = "match_brackets"
"^" = "goto_first_nonwhitespace"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
D = ["extend_to_line_end", "yank", "delete_selection"]
G = "goto_file_end"
S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable
V = ["select_mode", "extend_to_line_bounds"]

# Uncanny valley stuff, this makes w and b behave as they do Vim
B = ["move_prev_long_word_start", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
w = ["move_next_word_start", "move_char_right", "collapse_selection"]

# If you want to keep the selection-while-moving behaviour of Helix, this two lines will help a lot,
# especially if you find having text remain selected while you have switched to insert or append mode
#
# There is no real difference if you have overridden the commands bound to 'w', 'e' and 'b' like above
# But if you really want to get familiar with the Helix way of selecting-while-moving, comment the
# bindings for 'w', 'e', and 'b' out and leave the bindings for 'i' and 'a' active below. A world of difference!
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]

# Undoing the 'd' + motion commands restores the selection which is annoying
u = ["undo", "collapse_selection"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

# Search for word under cursor
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

# Make j and k behave as they do Vim when soft-wrap is enabled
j = "move_line_down"
k = "move_line_up"

[keys.normal.t]
b = [":new",":insert-output cargo"]
d = ":theme catppuccin_mocha"
f = ":format"
l = ":theme catppuccin_latte"
v = ["select_mode", "search_selection"]

[keys.select.t]
s = ":pipe sort" 

# Extend and select commands that expect a manual input can't be chained
# I've kept d[X] commands here because it's better to at least have the stuff you want to delete
# selected so that it's just a keystroke away to delete
[keys.normal.d]
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank", "delete_selection", "normal_mode"]
W = ["move_next_long_word_start", "yank", "delete_selection"]
d = ["extend_to_line_bounds", "yank", "delete_selection"]
down = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank", "delete_selection", "normal_mode"]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank", "delete_selection", "normal_mode"] }
h = ["delete_char_backward"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank", "delete_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank", "delete_selection", "normal_mode"]
l = ["delete_char_forward"]
t = ["extend_till_char"]
up = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank", "delete_selection", "normal_mode"]
w = ["move_next_word_start", "yank", "delete_selection"]

[keys.normal.y]
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
down = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"] }
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
up = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
y = ["extend_to_line_bounds", "yank", "normal_mode", "collapse_selection"]

[keys.insert]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]

[keys.select]
# Muscle memory
"$" = "goto_line_end"
"%" = "match_brackets"
"^" = "goto_first_nonwhitespace"
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
G = "goto_file_end"
S = "surround_add" # Basically 99% of what I use vim-surround for
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]

# Visual-mode specific muscle memory
a = "select_textobject_around"
i = "select_textobject_inner"

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
C-a = ["append_mode", "collapse_selection"]
tab = ["insert_mode", "collapse_selection"] # tab is read by most terminal editors as "C-i"

# Make selecting lines in visual mode behave sensibly
j = ["extend_line_down", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

